export const G_FACTOR = {
	FEINDBILD:               0,
	NEUSPRECH_VEREINFACHUNG: 30,
	TRADITIONSKULT:          70,
	ABLEHNUNG_DER_MODERNE:   80,
	WIDERSPRUCHSVERBOT:      80,
	KONSENSKULT:             80,
	ANGST_ALS_MACHT:         80,
	ABLEHNUNG_VOM_FREMDEM:   100,
	ELITENDENKEN:            100,
	HELDENTUM_VERHERRLICHEN: 100,
	MACHISMUS:               100,
	SELEKTIVER_POPULISMUS:   100,
	NATIONALISMUS:           100,
	MEDIENEINFLUESS:         100,
	MASSENKONTROLLE:         100
}
